following_vehicle:
  # Publish all joint states -----------------------------------
  f1_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  f1_left_position_controller:
    type: effort_controllers/JointVelocityController
    joint: f1_front_left
    pid: {p: 1.0, i: 0.0, d: 0.0}
  f1_right_position_controller:
    type: effort_controllers/JointVelocityController
    joint: f1_front_right 
    pid: {p: 1.0, i: 0.0, d: 0.0}


