leading_vehicle:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Velocity Controllers ---------------------------------------
  left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_left
    pid: {p: 1.0, i: 0.0, d: 0.0}
  right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_right 
    pid: {p: 1.0, i: 0.0, d: 0.0}

  # Position Controllers ---------------------------------------
  left_position_controller:
    joint: left_steering_hinge_joint
    type: effort_controllers/JointPositionController
    pid: {p: 1.0, i: 0.0, d: 0.5}
  right_position_controller:
    joint: right_steering_hinge_joint
    type: effort_controllers/JointPositionController
    pid: {p: 1.0, i: 0.0, d: 0.5}


